---
title: "Project2"
author: "Bailee Wallis"
date: "11/22/2019"
output: html_document
---

##### bmw2695

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
cardio <- read_excel("~/desktop/cardio.xlsx")
```



##### Introduction
*This dataset was found using kaggle and involves a variety of numeric (age, weight, systolic BP, diastolic BP), scaled (glucose level, cholesterol level, and gender), and binary variables (active, smoker, alcohol use, cardiac disease). The age, which was given in days, was divided by 365 in order to give age in years. Glucose and cholesterol levels were given as a scale from 1-3; 1 was set as a "normal" level, 2 was set as an "above normal" level, and 3 was set as a "well above normal" level. Gender was transformed so that 1 was equivalent to "female" and 2, equiavalent to "male". In order to use a more meaningful representation of blood pressure, the diastolic and systolic blood pressures were transformed to find the mean arterial pressure (MAP). Weight and height were used to create the BMI variable. Extreme outliers were removed (MAPs above 150 and below 60 were removed and BMIs above 50 were removed). Only the first 1000 observations were used because R was honestly very unhappy with a ~70k observation dataset. The subset code could be applied to the full data set, but the subset data fully illustrates the modeling concepts.*


```{R warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
cardio1 <- cardio %>% mutate_at(vars(age), funs(age/365)) %>% round(2) %>% rename(systolic_bp = ap_hi) %>% rename(diastolic_bp = ap_lo) 
cardio2<-cardio1 %>% mutate(cholesterol = ifelse(cholesterol == 1, "normal", ifelse(cholesterol == 2, "above normal", "well above normal"))) %>% mutate(gluc = ifelse(gluc == 1, "normal", ifelse(gluc == 2, "above normal", "well above normal"))) %>% rename(glucose = gluc) # categorical variables
cardio3 <- cardio2 %>% mutate(gender = ifelse(gender== 1, "female", "male")) 
cardio4 <- cardio3 %>% mutate(MAP = (systolic_bp/3) + ((2*diastolic_bp)/3)) %>% mutate(height = height/100) %>% mutate(BMI = weight/(height * height)) %>% dplyr::select(MAP, BMI, id) %>% round(2)
cardio5 <- cardio3 %>% full_join(cardio4, by = "id")
cardio6 <- cardio5 %>% dplyr::select(-1, -systolic_bp, -diastolic_bp) %>% rename(cardiac_disease = cardio) %>% filter(MAP < 150 & MAP > 60 & BMI < 50) %>% head(1000) 
cardio6

cardio6$MAP_c <- cardio6$MAP - mean(cardio6$MAP)
cardio6$BMI_c <- cardio6$BMI - mean(cardio6$BMI)

cardio8<-cardio6 %>% mutate(cholesterol = ifelse(cholesterol == "normal", 1, ifelse(cholesterol == "above normal",2 , 3))) %>% mutate(glucose = ifelse(glucose == "normal", 1, ifelse(glucose == "above normal", 2, 3))) %>% mutate(gender = ifelse(gender == "female", 1, 2)) # cat back to num ; female = 1 / male =2
cardio8 <- cardio8 %>% mutate_if(is.factor, as.numeric)
cardio8

```

##### MANOVA & ANOVA
*Testing whether MAP and BMI differ by presence/absence of cardiovascular disease.*

```{R warning = FALSE, message = FALSE}
ggplot(cardio8, aes(x = BMI, y = MAP)) + 
  geom_point(alpha = .5) + coord_fixed() + geom_density_2d(h=30) + facet_wrap(~cholesterol) # Eyeball assumptions: multivariate normality

covmats<-cardio8%>%group_by(cholesterol)%>%do(covs=cov(.[11:12]))
for(i in 1:3){print(covmats$covs[i])} # Eyeball assumptions: homogeneity of (co)variances

```

##### Assumptions:
*The assumptions required to perfrom a MANOVA test include random samples, independent observations, multivariate normality of DVs, homogeneity of within-gp covariance matrices, linear relationships among DVs, no extreme univariate or multivariate outliers, no multicollinearity. Based on the graphs above, it does not appear as if the DVs have multivariate normality and outliers are present. Because there are so many assumptions, it is unlikely they are all met. For example, the exact method of obtaining this data is not known and only a small subset of observations (1000 out of ~70k observations) is being analyzed, therefore random sampling is not met. The covariance matrices do not appear to be relatively homogeneous and outliers were removed from the data set. However, extreme departures from normality were not present in the bivariate density plots for each cholesterol level. It is uncertain as to whether the MANOVA test is an appropriate analysis technique*

##### Hypotheses:
*H0: For BMI and MAP, the means of each cholesterol level are equal*


*HA: For at least one DV, at least one cholosterol level mean is different*

```{R warning = FALSE, message = FALSE}
man1<-manova(cbind(MAP_c, BMI_c)~cholesterol, data=cardio8)
summary(man1) #overall MANOVA is significant
summary.aov(man1) # univariate ANOVA to see which are significant 
```
*A one-way multivariate analysis of variance (MANOVA) was conducted to determine the effect of BMI, and MAP on the dependent variable (cholesterol level).*

*With a p-value of approximately 2.2e-16, the null hypothesis is rejected (p < 0.05, alpha). This indicates that for at least one response variable, at least one group mean significantly differs. It was therefore appropriate to run univariate ANOVA tests to determine which are significantly different. MAP and BMI  are all significantly different, with p-values of approximately 2.2e-16 and 1.049e-07, respectively.*

*Significant differences were found among the three cholesterol level on the two dependent measures: Pillai trace = 0.096, pseudo F (2, 997) = 52.802, p < 0.0001.*

*Univariate analyses of variance (ANOVAs) for each dependent variable were conducted as follow-up tests to the MANOVA, using the Bonferroni method for controlling Type I error rates for multiple comparisons. The univariate ANOVAs for BMI and MAP were also significant, F (1, 998) = 28.7, p < .0001, and F (1, 998) = 91.109, p =< .0001, respectively.*

##### Individual T-Tests
```{R warning = FALSE, message = FALSE}
pairwise.t.test(cardio6$BMI,cardio6$cholesterol, p.adj="none") # individual ttests
pairwise.t.test(cardio6$MAP,cardio6$cholesterol, p.adj="none") # individual ttests
0.05/9
# P(at least one Type I error) = 1-(1-alpha)^(number of tests run)
1-(1-0.05)^9 # P(type I)
```

*Post hoc analysis was performed conducting pairwise comparisons to determine which cholesterol levels differed in BMI and MAP. For BMI, normal cholesterol levels significantly differed from above normal and well above normal cholesterol levels after adjusting for multiple comparisons, with p-values less than 0.0055 (bonferroni). Under the bonferroni adjustment, the above normal and well above normal cholesterol levels did not significantly differ in terms of BMI (p-value = 0.85, which is greater than 0.0055, the adujusted alpha). For MAP, normal cholesterol levels significantly differed from above normal and well above normal cholesterol levels after adjusting for multiple comparisons, with p-values < 0.0055 (bonferroni). Under the bonferroni adjustment, the above normal and well above normal cholesterol levels did not significantly differ in terms of MAP (p-value = 0.0065 > adjusted alpha).*

*Number of tests performed: 1 MANOVA, 2 ANOVAS, 2x3 (6) t-tests = 9 total tests*
*Bonferroni correction: alpha = 0.05/13 = 0.0055*
*Probability of Type I error if unadjusted = 0.3698*

##### Randomization Test - PERMANOVA 

*Because the MANOVA assumptions were likely violated, a PERMANOVA test was performed. With a PERMANOVA test, there are no distributional assumptions, it allows for differences in variances and covariances, it's not sensitive to multicollinearity, it allows more variables than samples, and it's not sensitive to many 0s/outliers*

##### Hypotheses:
*H0: centroids and dispersion of the cholesterol level groups, as defined by measure space, are equivalent for all groups*

*HA: centroids and dispersion of the cholesterol level groups, as defined by measure space, are not equivalent for all groups*

```{R warning = FALSE, message = FALSE}
library(vegan)
cardio6$cholesterol <- as.factor(cardio6$cholesterol)
dists <- cardio6%>% dplyr::select(BMI, MAP)%>%dist() # distances/dissimilarities
adonis(dists~cholesterol,data=cardio6) # PERMANOVA on distances/dissimilarities
```
*F model = 41.032*

##### PERMANOVA by hand
```{R warning = FALSE, message = FALSE}
cardio6 %>% filter(cholesterol == "normal") %>% nrow
cardio6 %>% filter(cholesterol == "above normal") %>% nrow
cardio6 %>% filter(cholesterol == "well above normal") %>% nrow


# observed F
SST<- sum(dists^2)/1000
SSW<- cardio6 %>%group_by(cholesterol)%>%dplyr::select(BMI, MAP)%>%
do(d=dist(.[2:3],"euclidean"))%>%ungroup()%>%
summarize(sum(d[[1]]^2)/143 + sum(d[[2]]^2)/732+ sum(d[[3]]^2)/125)%>%pull
F_obs<-((SST-SSW)/2)/(SSW/997) #observed F statistic
F_obs
```
*F by hand = 41.0318, matches adonis() F value of 41.032*

```{R warning = FALSE, message = FALSE}
# null distribution for F
set.seed(55)
Fs<-replicate(1000,{
new<-cardio6%>%mutate(Cholesterol=sample(cholesterol)) #permute the species vector 

SSW2<-new %>% group_by(Cholesterol) %>% dplyr::select(BMI, MAP) %>% do(d=dist(.[2:3],"euclidean"))%>%ungroup() %>%
  summarize(sum(d[[1]]^2)/143 + sum(d[[2]]^2)/732+ sum(d[[3]]^2)/125)%>%pull

((SST-SSW2)/2)/(SSW2/997) #calculate new F on randomized data
})
```

```{R warning = FALSE, message = FALSE}
mean(Fs>F_obs) # p-value 

{hist(Fs,prob = T); abline(v=F_obs, col="red", add=T)}
```

*Computing the PERMANOVA by hand resulted in a p-value of 0 (p < alpha). Therefore, the null hypothesis that the centroids and dispersion of the cholesterol level groups, as defined by measure space, are equivalent for all groups is rejected. This further supports the assertion that the cholesterol groups significantly differ in terms of BMI and MAP.*



##### Linear regression model predict MAP from BMI and active (yes/no)

##### Hypotheses:
*H0: while controlling for active, BMI does not explain variation in MAP (b2 = 0)*

*HA: while controlling for BMI, active does not explain variation in MAP (b3 = 0)*

```{R warning = FALSE, message = FALSE}
library(sandwich)
library(lmtest)
fit2<-lm(MAP_c~BMI_c*active,data=cardio8) # with interactions
summary(fit2)
coeftest(fit2, vcov = vcovHC(fit2))
```

##### MAP_c = 0.2680 + 0.6200(BMI_c) - 0.3406(active) - 0.1915(BMI_c * active)
*For an individual with a centered BMI of 0 and who is not active, their centered MAP is 0.2680. For each 1 unit increase for the centered BMI, centered MAP increases by 0.62. If an individual is active, their centered MAP decreases by 0.3406. For each 1 unit increase in the interaction of centered BMI and active, centered MAP decreases by 0.1915*

*Using robust standard errors, the standard error for the intercept decreases from 0.7332 to 0.70564 (from standard error to robust standard error). This is unexpected because robust errors tend to be more conservative and are typically larger. For BMI_c, the standard error increased from 0.1564 (original) to 0.16690 (robust), for active it decreased from 0.8292 to 0.80727, and for the interaction of BMI_C:active, the standard error increased from 0.1752 to a robust standard error of 0.18497.*

```{R warning = FALSE, message = FALSE}
resids<-fit2$residuals
fitvals<-fit2$fitted.values
ggplot(cardio8,aes(MAP_c,BMI_c,color=active))+geom_point() + theme(legend.position = "NONE")
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color='red') # homoskedasticity 
ggplot()+geom_histogram(aes(resids), bins=20) # normality
ks.test(resids, "pnorm", mean=0, sd(resids)) # formal test for normality; H0: distribution is normal; HA: distribution is not normal
```
*Based on the graph, the assumptions of homoskedasticity and linearity have been met as there is no fanning out and the relationship ship looks approximately linear (no curvy stuff going on). Based on the Kolmogorov-Smirnov test and the histogram indicate that the data is approximately normal.*

##### Plot of the Regression:
```{R warning = FALSE, message = FALSE}
cardio8$active <- as.factor(cardio8$active)
ggplot(cardio8, aes(x=BMI_c,y=MAP_c,group=active))+geom_point(aes(color=active))+
 geom_smooth(method="lm",se=F,fullrange=T,aes(color=active))+
theme(legend.position=c(.9,.19))+xlab("BMI_c") 
```

```{R warning = FALSE, message = FALSE}
(sum((cardio8$MAP_c-mean(cardio8$MAP_c))^2)-sum(fit2$residuals^2))/sum((cardio8$MAP_c-mean(cardio8$MAP_c))^2)
```
##### The calculated value above represents R^2 - 4.35% of the variation in MAP explained by the overall model (all predictors at once)

```{R warning = FALSE, message = FALSE}
fit3<-lm(MAP_c~BMI_c+active,data=cardio8) # without interactions
coef(fit3)
```
*Running the same regression model without interactions, MAP_c = 0.26209 + 0.467(BMI_c) - 0.335(active). For an individual with a BMI of 0 that is not active, their centered MAP is 0.26209. For each 1 unit increase in centered BMI, centered MAP increases by 0.467. If the individual is active, centered MAP decreases by 0.335.*

##### Regression model with interaction and bootstrapped standard errors. 

```{R warning = FALSE, message = FALSE}
set.seed(55)
boot_cardio<-cardio8[sample(nrow(cardio8),replace=TRUE),]

# repeat 5000 times, saving the coefficients each time
samp_distn<-replicate(5000, {
  boot_cardio<-cardio8[sample(nrow(cardio8),replace=TRUE),]
  fit<-lm(MAP_c~BMI_c*active,data=boot_cardio) 
  coef(fit)
})

## Estimated SEs, robust SE
samp_distn%>%t%>%as.data.frame%>%summarize_all(sd)
```
*The bootstrapped SE were slightly different from the original standard errors and robust standard errors. For the intercept, the bootstrapped standard error was 0.6959, which is lower than the original SE (0.7332) and the robust SE (0.70564). For the centered BMI, the bootstrapped SE of 0.1602 was between the original SE (0.1564) and robust SE (0.16690). For active, the bootstrapped SE of 0.7980 was below both the original and robust SE (0.8292 and 0.80727, respectively). The bootstrapped SE for the interaction of BMI_c:active was 0.1763, which is between the original SE (0.1752) and robust SE (0.18497.). Based on these results, the bootstrapped SE are not extremely conservative compared to other methods of finding SE.*


##### Perform a logistic regression predicting a binary categorical variable from at least two explanatory variables (interaction not necessary).
##### – Interpret coefficient estimates in context (10) 
```{R warning = FALSE, message = FALSE}
fit3 <- glm(cardiac_disease~BMI_c+MAP_c,family=binomial(link="logit"), data = cardio6)
coeftest(fit3)
0.0469332+0.0284000
exp(0.0753332)
0.0469332+0.1061120
exp(0.1530452)
exp(0.0469)
```
*For a BMI_c and MAP_c of 0, log-odds is 0.0469, with an odds of cardiac disease of e^0.0469 = 1.0481. For a one unit increase in BMI_c, log-odds is 0.0469+0.0284 = 0.0753332 and the odds of cardiac disease is e^0.0753332 = 1.078243. For a one unit increase in MAP_c and a BMI_c of 0, log-odds is 0.0469+0.10611 = 0.1530452 and odds of cardiac disease is e^0.1530452 = 1.165378. As BMIs and MAPs are typically larger (between 18-40 and 60-150 respectively), these values are reasonable. One additional BMI point increases cardiac odds by a factor of 1.08l one additional MAP point increases cardiac odds by a factor of 1.17.*

```{R warning = FALSE, message = FALSE}
cardio7 <- cardio6
cardio7$prob<-predict(fit3,type="response") #get predictions
cardio7$pred<-ifelse(cardio7$prob>.5,1,0)
table(truth=cardio7$cardiac_disease, prediction=cardio7$pred)%>%addmargins

(406+303)/1000 # accuracy
303/502# tpr/sensitivity 
406/498 #tnr/specificity 
303/395 # ppv / positive predicted value/ precision  
```
*The accuracy is 70.9% and the PPV is 76.71%, both of which are fair. The sensitivity is 60.36% which is considered bad due to how low it is - this means the model is not as likely to accurately predict cardiac disease (true positive). The specificity is 81.53% which is considered good - this means the model is more likely to accurately predict the absense of cardiac disease (true negative)*

###### Plot density of log-odds by your cardac disease
```{R warning = FALSE, message = FALSE}
cardio7$cardiac_disease <- as.factor(cardio6$cardiac_disease)
cardio7$logit<-predict(fit3,type="link")
cardio7%>%ggplot()+geom_density(aes(logit,color=cardiac_disease,fill=cardiac_disease), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab("predictor (logit)")
```

###### ROC Curve
```{R warning = FALSE, message = FALSE}
library(tidyverse)
library(MASS)
library(lmtest)
library(plotROC)

sens<-function(p,data=cardio7, y=cardiac_disease) mean(cardio7[cardio7$cardiac_disease==1,]$prob>p)
spec<-function(p,data=cardio7, y=cardiac_disease) mean(cardio7[cardio7$cardiac_disease==0,]$prob<p)

sensitivity<-sapply(seq(0,1,.01),sens,data)
specificity<-sapply(seq(0,1,.01),spec,data)

ROC1<-data.frame(sensitivity,specificity,cutoff=seq(0,1,.01))

ROC1%>%gather(key,rate,-cutoff)%>%ggplot(aes(cutoff,rate,color=key))+geom_path()+
  geom_vline(xintercept=c(.1,.5,.9),lty=2,color="gray50")

ROC1$TPR<-rev(sensitivity)
ROC1$FPR<-rev(1-specificity)

rocPlot <- ROC1%>%ggplot(aes(FPR,TPR))+geom_path(size=1.5)+geom_segment(aes(x=0,y=0,xend=1,yend=1),lty=2)+
  scale_x_continuous(limits = c(0,1))

rocPlot

library(pROC)
auc(cardio7$cardiac_disease,cardio7$prob)
```
*AUC is 0.7733 - which is considered to be a fair estimate. This is expected because the sensitivity was lower than the specificity. The AUC captures this trade-off between sensitivity and specificity.*

###### – Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)
```{R warning = FALSE, message = FALSE}
class_diag<-function(probs,truth){

tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
acc=sum(diag(tab))/sum(tab)
sens=tab[2,2]/colSums(tab)[2]
spec=tab[1,1]/colSums(tab)[1]
ppv=tab[2,2]/rowSums(tab)[2]

if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1

#CALCULATE EXACT AUC

ord<-order(probs, decreasing=TRUE)
probs <- probs[ord]
truth <- truth[ord]

TPR=cumsum(truth)/max(1,sum(truth))
FPR=cumsum(!truth)/max(1,sum(!truth))

dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)

n <- length(TPR)
auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

data.frame(acc,sens,spec,ppv,auc)

}

class_diag(cardio7$prob,cardio7$cardiac_disease)

set.seed(55)
k=10 #choose number of folds

data1<-cardio7[sample(nrow(cardio7)),] #randomly order rows
folds<-cut(seq(1:nrow(cardio7)),breaks=k,labels=F) #create folds

diags<-NULL
for(i in 1:k){

## Create training and test sets 
  train<-data1[folds!=i,] 
  test<-data1[folds==i,] 
  truth<-test$cardiac_disease

## Train model on training set 
  fit<-glm(cardiac_disease~BMI_c + MAP_c,data=train,family="binomial") 
  probs<-predict(fit,newdata = test,type="response")

## Test model on test set (save all k results) 
  diags<-rbind(diags,class_diag(probs,truth))

}
apply(diags,2,mean)
```
*For the 10-fold cross validation logistic regression, the average out-of-sample accuracy was 71.0% which is slightly higher than the original regression (70.9%). The 10-fold CV average out-of-sample sensitivity was 60.65%, which is slightly higher than the original regression (60.35%). The the 10-fold CV average out-of-sample specificity was 81.86%, which is slightly higher than the original (81.53%). The 10-fold CV average out-of-sample PPV was 77.22%, which is slightly higher than the original (76.61%). And the average out-of-sample AUC was 77.50%, which is slightly higher than the original (77.33%).*

*Because the model did not do more poorly in CV (it did not have a lower AUC), the model does not appear to be overfit*

##### LASSO Regression predicting cardiac disease with all other variables as predictors 
```{R warning = FALSE, message = FALSE}
library(glmnet)

cardio8<- cardio8 %>% mutate_if(is.factor, as.numeric)
x<-cardio8%>%dplyr::select(-cardiac_disease, -BMI_c, -MAP_c)%>%mutate_all(scale)%>%as.matrix
y<-as.matrix(cardio8$cardiac_disease)
cv1<-cv.glmnet(x,y)
cv1
plot(cv1$glmnet.fit, "lambda", label=TRUE) +
  abline(v = log(cv1$lambda.1se)) +
  abline(v = log(cv1$lambda.min),lty=2)

lasso1<-glmnet(x,y,lambda=cv1$lambda.1se)
coef(lasso1)
```
*In order to use all the variables as predictors, the categorical variables were coerced into numeric variables to make dataset cardio8 (see above). For cholesterol and glucose levels, the value of 1 is equivalent to a "normal" level, 2 is equivalent to an "above normal" level, and 3 is equivalent to an "above normal" level. Gender was coerced so that 1 indicates female and 2 indicates male. The centered BMI and MAP were not used due to redundancy. The lambda that gives the simplest model whose accuracy is near that of the 'best' is 0.0511 with 3 non-zero variables. The three retained variables are age, cholesterol, and MAP.*



##### 10-fold CV using the LASSO'd model above
```{R warning = FALSE, message = FALSE}
data1<-cardio8[sample(nrow(cardio8)),]
folds<-cut(seq(1:nrow(cardio8)),breaks=k,labels=F)

set.seed(55)
diags<-NULL
for(i in 1:k){

  train<-data1[folds!=i,]
  test<-data1[folds==i,]
  truth<-test$cardiac_disease

  fit<-glm(cardiac_disease~age+cholesterol+MAP,data=train,family="binomial")
  probs<-predict(fit,newdata = test,type="response")       
  preds<-ifelse(probs>.5,1,0)

diags<-rbind(diags,class_diag(probs,truth))

}

diags%>%summarize_all(mean)
```
*The average out-of-sample accuracy from part 5 was 70.7%, which is lower than the LASSO'd accuracy of 72.7%. This indicates the LASSO'd model is more accurate in predicting cardiac disease.*